num_clients: 20
num_rounds: 20
seed: 42
session_name: test_local
algorithm: local
device: cuda

server_config:
  fraction_fit: 1.0
  fraction_evaluate: 1
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

hydra:
  run:
    dir: ${session_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}s

defaults:
  - _self_
  - dataset: cifar10
  - client_config: fedavg
  - model: cnn_net